### ISSUE TITLE
`dist` folder of the package contains old code :) 

### ISSUE THREAD

**Issue by dwojno** [Permify/permify-node#29]
`dist/src/grpc/clients.js`
![image](https://github.com/Permify/permify-node/assets/32939785/d8a82cc0-e368-4664-a215-06c78f1548f8)
`src/grpc/clients.ts`
![image](https://github.com/Permify/permify-node/assets/32939785/6bb96f3c-5790-4e84-9a9b-46dee9a5a3ba)

**Comment by tolgaOzen** [comment]
Hello @dwojno , we have solved this issue in v0.4.1. Can you close the issue after testing it?
